{
  "formatVersion": "1.1",
  "component": {
    "group": "com.netflix.conductor",
    "module": "conductor-common",
    "version": "3.13.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "conductor-common-3.13.2.jar",
          "url": "conductor-common-3.13.2.jar",
          "size": 102025,
          "sha512": "6ef036288fd6eefd1bf9a73fbc93766f9514644193dd601338d575683a576b2523b4889d8b50f89a99047bb0b891610da381c598c11a72255e68a5791c4db836",
          "sha256": "d2b02f50d4e98e87c97bc206b7c9f6f5e03a3d8d61caa3fdc8eb4b7b6609df49",
          "sha1": "46881b449fd72be4f34e74538ac5e8687ad920d0",
          "md5": "996f097092a27635db278b835fd2361e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "strictly": "2.17.1",
            "requires": "2.17.1"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            },
            {
              "group": "ch.qos.logback",
              "module": "logback-core"
            },
            {
              "group": "org.apache.logging.log4j",
              "module": "log4j-to-slf4j"
            },
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-api",
          "version": {
            "strictly": "2.17.1",
            "requires": "2.17.1"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            },
            {
              "group": "ch.qos.logback",
              "module": "logback-core"
            },
            {
              "group": "org.apache.logging.log4j",
              "module": "log4j-to-slf4j"
            },
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-slf4j-impl",
          "version": {
            "strictly": "2.17.1",
            "requires": "2.17.1"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            },
            {
              "group": "ch.qos.logback",
              "module": "logback-core"
            },
            {
              "group": "org.apache.logging.log4j",
              "module": "log4j-to-slf4j"
            },
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-jul",
          "version": {
            "strictly": "2.17.1",
            "requires": "2.17.1"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            },
            {
              "group": "ch.qos.logback",
              "module": "logback-core"
            },
            {
              "group": "org.apache.logging.log4j",
              "module": "log4j-to-slf4j"
            },
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-web",
          "version": {
            "strictly": "2.17.1",
            "requires": "2.17.1"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            },
            {
              "group": "ch.qos.logback",
              "module": "logback-core"
            },
            {
              "group": "org.apache.logging.log4j",
              "module": "log4j-to-slf4j"
            },
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "com.netflix.conductor",
          "module": "conductor-annotations",
          "version": {
            "requires": "3.13.2"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            },
            {
              "group": "ch.qos.logback",
              "module": "logback-core"
            },
            {
              "group": "org.apache.logging.log4j",
              "module": "log4j-to-slf4j"
            },
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            },
            {
              "group": "ch.qos.logback",
              "module": "logback-core"
            },
            {
              "group": "org.apache.logging.log4j",
              "module": "log4j-to-slf4j"
            },
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "org.apache.bval",
          "module": "bval-jsr",
          "version": {
            "requires": "2.0.5"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            },
            {
              "group": "ch.qos.logback",
              "module": "logback-core"
            },
            {
              "group": "org.apache.logging.log4j",
              "module": "log4j-to-slf4j"
            },
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.13.0"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            },
            {
              "group": "ch.qos.logback",
              "module": "logback-core"
            },
            {
              "group": "org.apache.logging.log4j",
              "module": "log4j-to-slf4j"
            },
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.3"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            },
            {
              "group": "ch.qos.logback",
              "module": "logback-core"
            },
            {
              "group": "org.apache.logging.log4j",
              "module": "log4j-to-slf4j"
            },
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.13.3"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            },
            {
              "group": "ch.qos.logback",
              "module": "logback-core"
            },
            {
              "group": "org.apache.logging.log4j",
              "module": "log4j-to-slf4j"
            },
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-afterburner",
          "version": {
            "requires": "2.13.3"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            },
            {
              "group": "ch.qos.logback",
              "module": "logback-core"
            },
            {
              "group": "org.apache.logging.log4j",
              "module": "log4j-to-slf4j"
            },
            {
              "group": "org.slf4j",
              "module": "slf4j-log4j12"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "conductor-common-3.13.2.jar",
          "url": "conductor-common-3.13.2.jar",
          "size": 102025,
          "sha512": "6ef036288fd6eefd1bf9a73fbc93766f9514644193dd601338d575683a576b2523b4889d8b50f89a99047bb0b891610da381c598c11a72255e68a5791c4db836",
          "sha256": "d2b02f50d4e98e87c97bc206b7c9f6f5e03a3d8d61caa3fdc8eb4b7b6609df49",
          "sha1": "46881b449fd72be4f34e74538ac5e8687ad920d0",
          "md5": "996f097092a27635db278b835fd2361e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "conductor-common-3.13.2-javadoc.jar",
          "url": "conductor-common-3.13.2-javadoc.jar",
          "size": 1258,
          "sha512": "5f09f5a6bc167d16c7a0dd77233bffe8715389c7591d03e569f726c1ffcdc88ed11b6abaabc375d389b3d3c1f78046603eee8110ed15f0d7863d805596c9c2c7",
          "sha256": "47ef945b13e0ed1f0ad114216b31a68fe29c0b573fb6a71c1d359d216423a5d5",
          "sha1": "75f03573d55ae96dfd906cd590896ddc19f2a98b",
          "md5": "26f2864959b21baf6011cbb223fac4b9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "conductor-common-3.13.2-sources.jar",
          "url": "conductor-common-3.13.2-sources.jar",
          "size": 69892,
          "sha512": "518a79d90aa7af64a61a6a9cb8158c98a27e33a74bf6f95edddc2d5920c463e30ec0f314f30a0dbe75db7ceaae9d1bc71fbc6e45680bae1365f35ac178df3524",
          "sha256": "57cd41170a64c61d7d80c4d46fbb1da27a3c48dde3d0bd0a3ba652b2b7b01e1a",
          "sha1": "2f5d33d922088177264ad03f6f80ab0e859a7820",
          "md5": "0d58c93c222f6c13f8aef9b4a4d578ea"
        }
      ]
    }
  ]
}
