export CONDUCTOR_VER=3.13.2
export REPO_URL=https://repo1.maven.org/maven2/com/netflix/conductor/conductor-community-server
curl $REPO_URL/$CONDUCTOR_VER/conductor-community-server-$CONDUCTOR_VER-boot.jar \
--output conductor-server-$CONDUCTOR_VER-boot.jar; java -jar conductor-server-$CONDUCTOR_VER-boot.jar